sudo: false
language: ruby
cache:
  - bundler
  - apt
rvm:
  - ruby-2.5.3

gemfile:
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x

before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - 'rvm @global do gem install bundler -v 1.17.3'

notifications:
  email: false

script: "bundle exec rspec spec --color --profile"
