sudo: false
language: ruby
cache:
  - bundler
  - apt
rvm:
  - ruby-2.5.3

gemfile:
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x

notifications:
  email: false

script: "bundle exec rspec spec --color --profile"
