# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require File.expand_path("../dummy/config/environment.rb",  __FILE__)
require "rspec/rails"

# Load support files
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each { |f| require f }

RSpec.configure do |config|
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.infer_spec_type_from_file_location!

  config.with_options :type => :model do |c|
    c.include BootstrapHamlHelpers::Capybara::StringMatchers

    c.before do
      ActionController::Base.helper BootstrapHamlHelpers::ApplicationHelper
      controller = ActionController::Base.new
      controller.request = ActionController::TestRequest.new
      view_context = controller.view_context
      BootstrapHamlHelpers::Component::Base.init_context(view_context)
    end
  end
end
